import 'dart:io';

import 'package:transcript_core/transcript_core.dart';

/// Writes `docs/PRIVACY.md` from [PrivacyDisclosure], the Dart source of truth.
///
/// The store answers get copied out of that doc into App Store Connect and the Play
/// Console months after the code was written. Generating it means the listing can only
/// be wrong if the app's actual behaviour is wrong too — and CI re-runs this and fails
/// on any diff, so the doc cannot quietly drift away from the code.
void main() {
  final target = File('../../docs/PRIVACY.md');
  target.writeAsStringSync(renderPrivacyDoc());
  stdout.writeln('Wrote ${target.path}');
}

String renderPrivacyDoc() {
  final out = StringBuffer()
    ..writeln(
        '<!-- Generated by packages/transcript_core/tool/export_privacy.dart.')
    ..writeln(
        '     Edit lib/src/privacy/disclosure.dart instead; CI fails on drift. -->')
    ..writeln()
    ..writeln('# Privacy')
    ..writeln()
    ..writeln(
      'Transcript has no backend. There is no account, no analytics SDK, no '
      'advertising SDK, and no server belonging to us that your data passes '
      'through. You bring your own AI — an API key for a service you chose, a '
      'model on your own computer, or a model that runs on the phone itself — '
      'and the app talks to it directly from your device.',
    )
    ..writeln()
    ..writeln('## What the app does with each kind of data')
    ..writeln();

  for (final practice in PrivacyDisclosure.practices) {
    out
      ..writeln('### ${practice.label}')
      ..writeln()
      ..writeln('- **Where it goes:** ${practice.destination.label}')
      ..writeln(
        '- **Kept on the device:** ${practice.storedOnDevice ? 'yes' : 'no'}',
      );
    if (practice.userControls != null) {
      out.writeln('- **Your controls:** ${practice.userControls}');
    }
    out
      ..writeln()
      ..writeln(practice.plainLanguage)
      ..writeln();
  }

  out
    ..writeln('## Store listing answers')
    ..writeln()
    ..writeln(
      'Copy these verbatim. They are generated from the same source the app '
      'itself reads, so they describe what the build actually does.',
    )
    ..writeln()
    ..writeln('### App Store Connect — App Privacy')
    ..writeln()
    ..writeln('> ${PrivacyDisclosure.appStoreDataCollectionAnswer}')
    ..writeln()
    ..writeln('### Google Play Console — Data safety')
    ..writeln()
    ..writeln('> ${PrivacyDisclosure.playDataSafetyAnswer}')
    ..writeln();

  return out.toString();
}
