// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for `src/transcript_whisper_native.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class TranscriptWhisperNativeBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  TranscriptWhisperNativeBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  TranscriptWhisperNativeBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Transcribes a 16 kHz mono 16-bit PCM WAV file with a ggml/whisper.cpp
  /// model and returns a JSON string:
  /// {"segments":[{"start_ms":0,"end_ms":1200,"text":"..."}],"error":null}
  /// or, on failure:
  /// {"segments":[],"error":"message"}
  ///
  /// `language_hint` may be NULL or empty for auto-detection.
  /// `threads` <= 0 selects a reasonable default.
  ///
  /// The returned pointer is heap-allocated with malloc() and must be released
  /// by the caller via transcript_whisper_free_string().
  ffi.Pointer<ffi.Char> transcript_whisper_transcribe(
    ffi.Pointer<ffi.Char> model_path,
    ffi.Pointer<ffi.Char> wav_path,
    ffi.Pointer<ffi.Char> language_hint,
    int threads,
  ) {
    return _transcript_whisper_transcribe(
      model_path,
      wav_path,
      language_hint,
      threads,
    );
  }

  late final _transcript_whisper_transcribePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
          )
        >
      >('transcript_whisper_transcribe');
  late final _transcript_whisper_transcribe = _transcript_whisper_transcribePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
        )
      >();

  /// Frees a string previously returned by this library.
  void transcript_whisper_free_string(ffi.Pointer<ffi.Char> ptr) {
    return _transcript_whisper_free_string(ptr);
  }

  late final _transcript_whisper_free_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'transcript_whisper_free_string',
      );
  late final _transcript_whisper_free_string =
      _transcript_whisper_free_stringPtr
          .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// Releases any cached model context, freeing its memory. Safe to call at
  /// any time, including when nothing is loaded.
  void transcript_whisper_release() {
    return _transcript_whisper_release();
  }

  late final _transcript_whisper_releasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
        'transcript_whisper_release',
      );
  late final _transcript_whisper_release = _transcript_whisper_releasePtr
      .asFunction<void Function()>();

  /// Returns a static, non-owned version string. Never returns NULL.
  ffi.Pointer<ffi.Char> transcript_whisper_version() {
    return _transcript_whisper_version();
  }

  late final _transcript_whisper_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'transcript_whisper_version',
      );
  late final _transcript_whisper_version = _transcript_whisper_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();
}
