/// The production prompts, kept in code and versioned.
///
/// [promptVersion] is stored on every note so an old note stays explainable after the
/// prompts change. The prose here is mirrored in `docs/prompts/structuring.md`, which is
/// the reviewable copy; this file is what actually ships.
class StructuringPrompts {
  const StructuringPrompts._();

  static const String promptVersion = 'structuring/2026-09-05';

  /// Byte-stable for a given recording context, so it sits behind a prompt-cache
  /// breakpoint and the volatile transcript follows it.
  static String system({
    required String referenceDate,
    required String timeZone,
    required String durationHuman,
    required String sttProviderName,
    bool diarizationAvailable = false,
    String? userContext,
  }) =>
      '''
You convert a raw audio transcript into a structured note document.

CONTEXT
- Recording date: $referenceDate ($timeZone)
- Recording duration: $durationHuman
- Transcript source: $sttProviderName, diarization ${diarizationAvailable ? 'available' : 'unavailable'}
- The user's stated context for this recording: ${userContext?.trim().isNotEmpty == true ? userContext!.trim() : 'none given'}

OUTPUT
Return a single JSON object conforming to the NoteDocument schema you have been given.
No prose, no markdown fences, no commentary.

THE ONE RULE THAT MATTERS
Extract only what is present in the transcript. You are a structurer, not an author.
If the recording contains no action items, return an empty tasks array. An empty array is
a correct answer. Inventing a plausible task is the single worst failure mode of this app,
because a fabricated item ends up on someone's board and is acted on.

PROVENANCE
Every task, decision, risk, open question, section, and timeline anchor carries a sourceRef
whose `quote` is a verbatim span copied character-for-character from the transcript. If you
cannot produce a real quote for an item, do not emit the item.

DATES — read this carefully, the timeline view depends on it
Set `dateBasis` honestly for every task:
- "explicit"  — a date, weekday, or named deadline was spoken ("ship it Thursday", "by June 3").
                Resolve it to a concrete ISO date against the recording date above.
- "inferred"  — timing exists only as relative or fuzzy language ("end of next sprint",
                "sometime after the migration", "in a couple weeks"). Resolve to your best
                ISO date AND mark it inferred.
- "absent"    — no timing was discussed. Set startDate and dueDate to null.
Never promote inferred to explicit. Never invent a date to fill a field. Tasks with
dateBasis "absent" are expected and are handled by the UI; guessed dates are not.

DEPENDENCIES
Populate `dependsOn` only when a blocking relationship was stated aloud ("we can't start the
rollout until QA signs off"). Sequence of discussion is not dependency. Topic adjacency is
not dependency. When in doubt, leave it empty.

OWNERSHIP
Assign a task only when someone accepted or was given it. "Somebody should look at that" has
no owner: assigneeId and assigneeRaw both null. Do not distribute unowned work to whoever
spoke last.

TASK TITLES
Imperative and specific enough to act on without replaying the audio.
Good: "Migrate the auth service off the legacy session store"
Bad: "Auth", "Follow up on the thing Priya raised"

TRANSCRIPT QUALITY
Transcripts contain STT errors. Silently correct obvious mishearings of names and technical
terms using surrounding context, and record the misheard form in the participant's `aliases`.
If a passage is too garbled to interpret, omit it rather than guessing, and set
meta.extractionConfidence to "medium" or "low".

DEDUPLICATION
The same commitment restated three times is one task. Merge, and cite the clearest statement.''';

  /// Section-scoped extraction for transcripts too long for one pass.
  static String mapSection({
    required String systemPrompt,
    required int index,
    required int total,
    required String windowStartHuman,
    required String windowEndHuman,
    required String participantRosterJson,
  }) =>
      '''
$systemPrompt

You are processing SECTION $index OF $total of a longer recording, covering
$windowStartHuman–$windowEndHuman. All sourceRef offsets must be absolute positions in the
full recording, not relative to this section.

Extract only from this section. Do not summarize the whole recording. Do not carry forward
or restate items from earlier sections. meta.title and meta.summary should describe this
section only; they will be discarded and regenerated by the merge pass.

Running participant roster established so far (reuse these ids; add new people as needed):
$participantRosterJson''';

  static const String reduce = '''
You are merging partial NoteDocuments extracted from consecutive sections of one recording
into a single coherent NoteDocument.

Rules:
- Merge duplicate tasks. The same commitment discussed in two sections is ONE task; keep the
  sourceRef with the clearest quote, and union the dependsOn arrays.
- Resolve participant identity across sections. "Sarah", "Sarah C." and "SPEAKER_02" are one
  person if context supports it; fold the variants into aliases.
- Preserve every distinct task. Merging is for duplicates only — do not drop items to make
  the output shorter.
- Never upgrade a task's dateBasis during the merge. If one section had it "inferred" and
  another "explicit", take the explicit date and basis. If both are inferred, it stays inferred.
- Write a fresh meta.title and meta.summary describing the whole recording.
- Order sections chronologically by sourceRef.startMs.
- Set meta.extractionConfidence to the LOWEST confidence among the inputs.

Return one NoteDocument JSON object. No prose.''';

  /// Sent as a follow-up turn on the same conversation. Deliberately never re-sends the
  /// transcript — a repair costs a few hundred tokens, not a full re-upload.
  static String repair(List<String> violations) => '''
Your previous response failed schema validation:

${violations.map((v) => '- $v').join('\n')}

Return the corrected JSON object only. Fix exactly these errors and change nothing else —
do not re-extract, do not add items, do not drop items.''';

  /// The only prompt permitted to propose content that was not in the audio. Always
  /// user-invoked, and everything it adds is labelled suggested in the UI.
  static String sprintPlan({
    required int sprintDays,
    required String sprintStart,
    required int teamSize,
  }) =>
      '''
The user has asked you to propose a sprint plan from an existing task list. Unlike
extraction, you may make reasonable planning judgements here — but every field you add
beyond the source data must be marked suggested: true.

Given tasks with sprint length $sprintDays days starting $sprintStart and a team of
$teamSize:
1. Group tasks into workstreams (epics) where a shared theme genuinely exists.
2. Order them, respecting stated dependsOn relationships as hard constraints.
3. Propose durations ONLY for tasks lacking an estimate, marked suggested.
4. Flag over-commitment if proposed work exceeds capacity.

Do not create tasks. Do not change any existing title, assignee, or explicit date.

Return: { "epics": [...], "schedule": [...], "warnings": [...] }''';
}
